### ISSUE TITLE
安装hanlp插件后，节点就内存溢出outofmemory

### ISSUE THREAD

**Issue by jacklu2016** [AnyListen/elasticsearch-analysis-hanlp#10]
java.lang.OutOfMemoryError: Java heap space
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.load(LinearModel.java:434) ~[?:?]
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.load(LinearModel.java:388) ~[?:?]
	at com.hankcs.hanlp.model.perceptron.model.LinearModel.<init>(LinearModel.java:65) ~[?:?]
	at com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer.<init>(PerceptronLexicalAnalyzer.java:70) ~[?:?]
	at com.hankcs.hanlp.model.perceptron.PerceptronLexicalAnalyzer.<init>(PerceptronLexicalAnalyzer.java:95) ~[?:?]
	at com.hankcs.hanlp.HanLP.newSegment(HanLP.java:685) ~[?:?]
	at org.elasticsearch.plugin.hanlp.conf.ConfigHelper.lambda$getSegment$0(ConfigHelper.java:149) ~[?:?]
	at org.elasticsearch.plugin.hanlp.conf.ConfigHelper$$Lambda$1685/783382452.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_65]
	at org.elasticsearch.plugin.hanlp.conf.ConfigHelper.getSegment(ConfigHelper.java:132) ~[?:?]
	at org.elasticsearch.plugin.hanlp.analysis.HanLPAnalyzerProvider.<init>(HanLPAnalyzerProvider.java:35) ~[?:?]
	at org.elasticsearch.plugin.hanlp.analysis.HanLPAnalyzerProvider.getPerceptronAnalyzerProvider(HanLPAnalyzerProvider.java:51) ~[?:?]
	at org.elasticsearch.plugin.hanlp.AnalysisHanLPPlugin$$Lambda$446/905650857.get(Unknown Source) ~[?:?]
	at org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:362) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.index.analysis.AnalysisRegistry.buildAnalyzerFactories(AnalysisRegistry.java:187) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:157) ~[elasticsearch-6.1.1.jar:6.1.1]
	at org.elasticsearch.index.IndexService.<init>(IndexService.java:160) ~[elasticsearch-6.1.1.jar:6.1.1]

**Comment by JrJessyLuo** [comment]
I had the same problem. But I solved it by modifying the file “jvm.options” in the “config” directory. I changed the "-Xms1g -Xmx1g"  to "-Xms4g -Xmx4g".
